import { AlertTriangle, ArrowRight, CheckCircle2, CircleHelp, ClipboardList, FileQuestion, FileSearch, GitMerge, Link2, MessageSquareQuote, RefreshCcw, SearchCheck, ShieldAlert, Truck, Users } from "lucide-react";
import { useState } from "react";
import { PageHeader } from "../../components/common/PageHeader";
import { Badge } from "../../components/ui/Badge";
import { Button } from "../../components/ui/Button";
import { Card } from "../../components/ui/Card";
import { stakeholders } from "../../constants/scenario";
import { requirements } from "../../constants/scenario";
import { confirmations, conflicts, decisions, evidenceRegister, findings, openQuestions, risks, traceabilityRows } from "../../constants/trainingScenario";
import type { RouteKey } from "../../types/models";
import { classNames } from "../../utils/format";

const tabs = ["Session Summary", "Findings & Evidence", "Assumptions & Gaps", "Conflicts & Questions", "Requirements", "Confirmation", "Traceability", "Change Impact", "Risks & Decisions"] as const;
type Tab = typeof tabs[number];

const statusBadge = (status: string) => status === "confirmed" || status === "Complete" || status === "resolved" || status === "Approved"
  ? <Badge tone="green">{status === "confirmed" ? "Confirmed" : status === "resolved" ? "Resolved" : status}</Badge>
  : <Badge tone="amber">{status === "needs-clarification" ? "Needs clarification" : status === "open" ? "Open" : status}</Badge>;

export function AnalysisHubPage({ navigate }: { navigate: (route: RouteKey) => void }) {
  const [tab, setTab] = useState<Tab>("Session Summary");
  return <>
    <PageHeader eyebrow="Step 3 of 5 · Analyze & Confirm" title="Analysis & Confirmation" description="Review evidence, resolve gaps, and confirm traceable requirements." actions={<><Button variant="secondary" onClick={() => navigate("simulation")}>Transcript</Button><Button onClick={() => navigate("artifacts")}>Final deliverables <ArrowRight size={16} /></Button></>} />

    <Card className="mb-4 flex divide-x divide-[#e3eaf0] overflow-x-auto">
      {[["6/6","Stakeholders","bg-[#e8f2fb] text-[#376c98]"],["9","Evidence","bg-[#e9f6ef] text-[#31755d]"],["4","Findings","bg-[#f1edfb] text-[#68599b]"],["4","Assumptions","bg-[#f3edfa] text-[#755c98]"],["5","Requirements","bg-[#eaf2f9] text-[#456f94]"],["1","Blocking gap","bg-[#fbe9ed] text-[#9d4e63]"]].map(([value,label,tone]) => <div key={label} className="flex min-w-[150px] flex-1 items-center gap-2.5 px-3 py-2.5"><span className={classNames("grid h-8 min-w-8 place-items-center rounded-lg px-2 text-sm font-black",tone)}>{value}</span><span className="text-xs font-semibold text-[#536b83]">{label}</span></div>)}
    </Card>

    <div className="mb-4 flex gap-1.5 overflow-x-auto rounded-xl border border-[#dfe7ef] bg-white p-1.5">{tabs.map((item) => <button key={item} onClick={() => setTab(item)} className={classNames("shrink-0 rounded-lg px-3 py-2 text-sm font-semibold transition", tab === item ? "bg-[#dfeaf4] text-[#244f78]" : "text-[#708399] hover:bg-[#f2f5f8]")}>{item}</button>)}</div>

    {tab === "Session Summary" && <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_320px]">
      <Card className="overflow-hidden"><div className="border-b border-[#e3e9ef] p-5"><h2 className="font-bold text-[#203b59]">Elicitation session register</h2><p className="mt-1 text-sm text-[#788a9d]">Each session has its own objective, technique, information coverage, and output.</p></div><div className="divide-y divide-[#e7edf2]">{stakeholders.map((person,index) => <div key={person.id} className="grid gap-4 p-5 md:grid-cols-[210px_1fr_auto] md:items-center"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl text-xs font-bold text-[#294865]" style={{backgroundColor:person.color}}>{person.initials}</span><div><strong className="block text-sm text-[#2d4662]">{person.name}</strong><span className="text-xs text-[#8090a1]">{person.role}</span></div></div><div><p className="text-sm font-semibold text-[#49627b]">{["Time, budget & out-of-scope","KPIs, scope & override authority","Warehouse process, returns & stock accuracy","Forecast, min-max & transfer-first","Offline scanning & operational errors","Adjustment, audit & approval"][index]}</p><div className="mt-2 flex flex-wrap gap-1.5">{([ ["Constraint","Scope","Governance"],["KPI","Scope","Decision"],["Process","Pain point","Data"],["Rule","Data","Exception"],["Observation","Pain point","NFR"],["Rule","Control","Audit"] ][index]).map((item) => <span key={item} className="rounded-full bg-[#f0f4f7] px-2 py-1 text-[11px] font-semibold text-[#63798f]">{item}</span>)}</div></div><div className="text-right"><Badge tone={index < 4 ? "green" : "amber"}>{index < 4 ? "Sufficient data" : "Follow-up needed"}</Badge><p className="mt-2 text-xs text-[#8594a3]">{["Constraint elicitation","KPI elicitation","Interview + playback","Decision analysis","Contextual inquiry","Business rules"][index]}</p></div></div>)}</div></Card>
      <aside className="space-y-5"><Card className="p-5"><div className="flex items-center gap-3"><SearchCheck className="text-[#48759d]" size={20}/><h2 className="font-bold text-[#203b59]">Definition of Done</h2></div><div className="mt-5 space-y-3">{[["Source and timestamp for every evidence item",true],["Findings distinguish facts from interpretations",true],["Conflicts have accountable owners",true],["Stakeholders validate findings",false],["Requirements include acceptance criteria",true]].map(([label,done]) => <div key={String(label)} className="flex items-start gap-3"><span className={classNames("mt-0.5 grid h-5 w-5 place-items-center rounded-full",done ? "bg-[#dcf0e6] text-[#277456]" : "bg-[#fff0d8] text-[#9a681d]")}>{done ? <CheckCircle2 size={13}/> : <CircleHelp size={13}/>}</span><span className="text-sm leading-5 text-[#5c7288]">{String(label)}</span></div>)}</div></Card><Card className="border-[#eadcb9] bg-[#fffdf6] p-5"><div className="flex gap-3"><AlertTriangle className="mt-0.5 shrink-0 text-[#a6711b]" size={19}/><div><h3 className="font-bold text-[#6f5526]">Blocking Gap</h3><p className="mt-2 text-sm leading-6 text-[#75684e]">FND-04 has not been validated by the operator because legacy scanners do not display transactions awaiting synchronization.</p><button onClick={() => setTab("Conflicts & Questions")} className="mt-3 text-sm font-bold text-[#8a6220]">Open follow-up question →</button></div></div></Card></aside>
    </div>}

    {tab === "Findings & Evidence" && <div className="space-y-5"><div className="grid gap-4 lg:grid-cols-2">{findings.map((finding) => <Card key={finding.id} className="p-5"><div className="flex items-start justify-between gap-3"><div className="flex gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#e7f0f7] text-xs font-black text-[#37648b]">{finding.id.replace("FND-","")}</span><div><p className="text-xs font-bold text-[#6d849b]">{finding.id} · Owner: {finding.owner}</p><h3 className="mt-1 font-bold text-[#29435f]">{finding.title}</h3></div></div>{statusBadge(finding.status)}</div><p className="mt-4 text-sm leading-6 text-[#5b7187]">{finding.interpretation}</p><div className="mt-4 flex items-center gap-2 text-xs font-bold text-[#4e7498]"><Link2 size={14}/>{finding.evidenceIds.join(" · ")}</div></Card>)}</div><Card className="overflow-hidden"><div className="flex items-center gap-3 border-b border-[#e3e9ef] p-5"><MessageSquareQuote className="text-[#4b769b]"/><div><h2 className="font-bold text-[#203b59]">Evidence register</h2><p className="text-sm text-[#7b8c9d]">Facts retain their original meaning and include source, confidence, and trace links.</p></div></div><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className="bg-[#f5f8fa] text-xs uppercase tracking-wider text-[#7a8da1]"><tr><th className="px-5 py-4">ID</th><th className="px-5 py-4">Evidence excerpt</th><th className="px-5 py-4">Source</th><th className="px-5 py-4">Type</th><th className="px-5 py-4">Confidence</th><th className="px-5 py-4">Validation</th><th className="px-5 py-4">Requirement</th></tr></thead><tbody className="divide-y divide-[#e6edf2]">{evidenceRegister.map((item) => <tr key={item.id} className="align-top hover:bg-[#fafcfd]"><td className="px-5 py-4 font-mono font-bold text-[#547392]">{item.id}</td><td className="max-w-md px-5 py-4 font-semibold leading-6 text-[#3d5670]">“{item.quote}”</td><td className="px-5 py-4 text-[#6d8094]">{item.source}</td><td className="px-5 py-4"><Badge tone="navy">{item.category}</Badge></td><td className="px-5 py-4">{item.confidence}</td><td className="px-5 py-4">{statusBadge(item.status)}</td><td className="px-5 py-4 font-semibold text-[#4c7397]">{item.linkedRequirements.join(", ")}</td></tr>)}</tbody></table></div></Card></div>}

    {tab === "Conflicts & Questions" && <div className="grid gap-5 xl:grid-cols-[1fr_400px]"><div className="space-y-5">{conflicts.map((conflict) => <Card key={conflict.id} className="p-6"><div className="flex items-start justify-between"><div><p className="text-xs font-bold text-[#70869c]">{conflict.id}</p><h2 className="mt-1 text-lg font-bold text-[#233f5c]">{conflict.topic}</h2></div>{statusBadge(conflict.status)}</div><div className="mt-5 grid gap-3 md:grid-cols-2">{conflict.positions.map((item) => <div key={item.stakeholder} className="rounded-xl border border-[#dfe7ee] bg-[#fafcfd] p-4"><p className="text-xs font-bold uppercase tracking-wide text-[#6e86a0]">{item.stakeholder}</p><p className="mt-2 text-sm leading-6 text-[#526a82]">{item.position}</p></div>)}</div><div className="mt-4 rounded-xl bg-[#fff7e9] p-4"><strong className="text-sm text-[#805f24]">Impact</strong><p className="mt-1 text-sm leading-6 text-[#74684e]">{conflict.impact}</p></div><div className="mt-3 rounded-xl bg-[#edf6f1] p-4"><strong className="text-sm text-[#316a54]">Resolution / next decision</strong><p className="mt-1 text-sm leading-6 text-[#526e62]">{conflict.resolution}</p></div></Card>)}</div><Card className="h-fit p-5"><div className="flex items-center gap-3"><CircleHelp className="text-[#a27022]"/><h2 className="font-bold text-[#203b59]">Open question log</h2></div><div className="mt-5 space-y-4">{openQuestions.map((item) => <div key={item.id} className="rounded-xl border border-[#e1e8ee] p-4"><div className="flex items-center justify-between"><Badge tone="amber">{item.id}</Badge><span className="text-xs text-[#8795a4]">Due {item.due}</span></div><p className="mt-3 text-sm font-semibold leading-6 text-[#425c75]">{item.question}</p><p className="mt-3 text-xs text-[#74879a]">Owner: {item.owner} · {item.relatedTo}</p></div>)}</div></Card></div>}

    {tab === "Confirmation" && <div className="grid gap-5 lg:grid-cols-2">{confirmations.map((item) => { const finding = findings.find((entry) => entry.id === item.findingId); return <Card key={item.id} className="p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold text-[#71879d]">{item.id} · {item.findingId}</p><h2 className="mt-1 font-bold text-[#29435e]">{finding?.title}</h2></div>{statusBadge(item.status)}</div><div className="mt-5 flex gap-3 rounded-xl bg-[#f4f8fa] p-4"><Users className="mt-0.5 shrink-0 text-[#547b9d]" size={18}/><div><strong className="text-sm text-[#3a5570]">{item.stakeholder}</strong><p className="mt-2 text-sm leading-6 text-[#5d7287]">“{item.response}”</p>{item.confirmedAt && <p className="mt-2 text-xs text-[#8795a3]">Responded at {item.confirmedAt}</p>}</div></div></Card>; })}</div>}

    {tab === "Traceability" && <Card className="overflow-hidden"><div className="flex items-center gap-3 border-b border-[#e3e9ef] p-5"><GitMerge className="text-[#4e789d]"/><div><h2 className="font-bold text-[#203b59]">Objective → Finding → Evidence → Requirement → Acceptance</h2><p className="text-sm text-[#7b8c9d]">The traceability chain shows whether requirements are evidence-based and measurable.</p></div></div><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="bg-[#f5f8fa] text-xs uppercase tracking-wider text-[#7a8da1]"><tr>{["Business objective","Finding","Evidence","Requirement","Acceptance criteria","Coverage"].map((h) => <th key={h} className="px-5 py-4">{h}</th>)}</tr></thead><tbody className="divide-y divide-[#e6edf2]">{traceabilityRows.map((row,index) => <tr key={index} className="align-top"><td className="px-5 py-5 font-semibold text-[#395570]">{row.objective}</td><td className="px-5 py-5 font-mono text-xs font-bold text-[#587795]">{row.finding}</td><td className="px-5 py-5 text-[#657a8f]">{row.evidence}</td><td className="px-5 py-5 font-bold text-[#426b91]">{row.requirement}</td><td className="max-w-sm px-5 py-5 leading-6 text-[#526a81]">{row.acceptance}</td><td className="px-5 py-5">{statusBadge(row.status)}</td></tr>)}</tbody></table></div></Card>}

    {tab === "Risks & Decisions" && <div className="grid gap-5 xl:grid-cols-[1.15fr_.85fr]"><Card className="overflow-hidden"><div className="flex items-center gap-3 border-b border-[#e3e9ef] p-5"><ShieldAlert className="text-[#a36b23]"/><h2 className="font-bold text-[#203b59]">Risk register</h2></div><div className="divide-y divide-[#e6edf2]">{risks.map((risk) => <div key={risk.id} className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><span className="font-mono text-xs font-bold text-[#6b8298]">{risk.id}</span><h3 className="mt-1 font-bold text-[#334e69]">{risk.title}</h3></div><div className="flex gap-2"><Badge tone={risk.probability === "High" ? "red" : "amber"}>P: {risk.probability}</Badge><Badge tone={risk.impact === "High" ? "red" : "amber"}>I: {risk.impact}</Badge></div></div><p className="mt-3 text-sm leading-6 text-[#5e7489]"><strong>Response:</strong> {risk.response}</p><p className="mt-2 text-xs text-[#8190a0]">Owner: {risk.owner}</p></div>)}</div></Card><Card className="h-fit p-5"><div className="flex items-center gap-3"><FileSearch className="text-[#4c789e]"/><h2 className="font-bold text-[#203b59]">Decision log</h2></div><div className="mt-5 space-y-4">{decisions.map((decision) => <div key={decision.id} className="rounded-xl border border-[#dfe7ee] p-4"><div className="flex items-center justify-between"><span className="font-mono text-xs font-bold text-[#607b95]">{decision.id}</span>{statusBadge(decision.status)}</div><h3 className="mt-3 font-bold text-[#3b5570]">{decision.title}</h3><p className="mt-2 text-sm leading-6 text-[#63778b]">{decision.rationale}</p><p className="mt-3 text-xs text-[#8794a2]">{decision.decidedBy} · {decision.date}</p></div>)}</div></Card></div>}
    {tab === "Change Impact" && <ChangeImpactSection />}
    {tab === "Assumptions & Gaps" && <AssumptionsAndGapsSection />}
    {tab === "Requirements" && <RequirementAnalysisSection />}
  </>;
}

function AssumptionsAndGapsSection() {
  const assumptions = [
    { id: "ASM-01", statement: "POS latency is the primary cause of stockouts.", basis: "Q3 operations report", impact: "The wrong solution may be prioritized if the primary cause is allocation or quarantine.", owner: "Supply Chain Director", status: "needs-clarification", linked: "FND-01 · RSK-01" },
    { id: "ASM-02", statement: "All warehouses use the same SKU codes and units of measure.", basis: "Project brief", impact: "If false, transfer-first may create mapping errors or incorrect quantities.", owner: "Master Data Lead", status: "confirmed", linked: "FR-08 · DATA-02" },
    { id: "ASM-03", statement: "Internal transfers are always cheaper than creating a new purchase order.", basis: "Planner’s initial opinion", impact: "Costs may increase when transfers travel long distances or purchase orders receive preferential pricing.", owner: "Finance Manager", status: "needs-clarification", linked: "CF-02 · DEC-01" },
    { id: "ASM-04", statement: "Current scanners support a local queue and client transaction ID.", basis: "Unverified device documentation", impact: "The offline design may not be feasible on current devices.", owner: "Warehouse IT", status: "unconfirmed", linked: "FND-04 · NFR-03" },
  ];
  return <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_350px]">
    <Card className="overflow-hidden"><div className="flex items-center gap-3 border-b border-[#e3e9ef] p-5"><FileQuestion className="text-[#795f9d]"/><div><h2 className="font-bold text-[#203b59]">Assumption register</h2><p className="text-sm text-[#7b8c9d]">Statements the learner currently assumes to be true but must validate before using them as a design basis.</p></div></div><div className="divide-y divide-[#e6edf2]">{assumptions.map((item) => <div key={item.id} className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-mono text-xs font-bold text-[#6d8196]">{item.id}</p><h3 className="mt-1 font-bold text-[#354f69]">{item.statement}</h3></div>{statusBadge(item.status)}</div><div className="mt-4 grid gap-3 md:grid-cols-2"><div className="rounded-xl bg-[#f5f8fa] p-3"><p className="text-xs font-bold uppercase tracking-wide text-[#778b9f]">Basis</p><p className="mt-2 text-sm leading-6 text-[#5e7489]">{item.basis}</p></div><div className="rounded-xl bg-[#fff8ec] p-3"><p className="text-xs font-bold uppercase tracking-wide text-[#92703a]">Risk if false</p><p className="mt-2 text-sm leading-6 text-[#75684f]">{item.impact}</p></div></div><div className="mt-3 flex flex-wrap items-center justify-between gap-2 text-xs"><span className="text-[#7c8d9d]">Validate with: <strong className="text-[#526c84]">{item.owner}</strong></span><span className="font-bold text-[#55799a]">Related: {item.linked}</span></div></div>)}</div></Card>
    <aside className="space-y-5"><Card className="p-5"><div className="flex items-center gap-3"><CircleHelp className="text-[#a27022]"/><h2 className="font-bold text-[#203b59]">Information gap & open questions</h2></div><div className="mt-5 space-y-4">{openQuestions.map((item) => <div key={item.id} className="rounded-xl border border-[#e1e8ee] p-4"><div className="flex items-center justify-between"><Badge tone="amber">{item.id}</Badge><span className="text-xs text-[#8795a4]">Due {item.due}</span></div><p className="mt-3 text-sm font-semibold leading-6 text-[#425c75]">{item.question}</p><p className="mt-3 text-xs text-[#74879a]">Owner: {item.owner} · {item.relatedTo}</p></div>)}</div></Card><Card className="border-[#d9e5ef] bg-[#f3f8fb] p-5"><h3 className="font-bold text-[#355773]">What do AI and experts assess?</h3><ul className="mt-3 space-y-2 text-sm leading-6 text-[#64798d]"><li>• Does the learner distinguish facts from assumptions?</li><li>• Does each assumption have a source and impact?</li><li>• Is validation assigned to the right person?</li><li>• Are requirement-blocking gaps tracked?</li></ul></Card></aside>
  </div>;
}

function RequirementAnalysisSection() {
  const details: Record<string, { rationale: string; acceptance: string; trace: string; gap?: string }> = {
    "BR-01": { rationale: "Protect stockout and fill-rate targets within the pilot scope.", acceptance: "Stockout < 5% and fill rate ≥ 96% after eight pilot weeks.", trace: "OBJ-01 · EV-03 · FND-02" },
    "SR-04": { rationale: "The Planner must prioritize surplus stock in the network before purchasing.", acceptance: "Every replenishment suggestion must check available transfers before proposing a purchase order.", trace: "EV-03 · EV-04 · FND-02" },
    "FR-08": { rationale: "Reduce new purchases when another warehouse has transferable surplus.", acceptance: "Check network surplus before creating a purchase order; display quantity, ETA, cost, and the reason for any override.", trace: "OBJ-01 · EV-03 · EV-04 · FND-02" },
    "NFR-03": { rationale: "The warehouse must record inventory movements even when connectivity is unstable.", acceptance: "Each transaction has a client ID, retry creates no duplicates, and the pending queue is visible.", trace: "EV-08 · FND-04", gap: "Device capability and retry threshold have not been validated." },
    "TR-02": { rationale: "Ensure opening data is reliable before the pilot.", acceptance: "100% of pilot SKUs are reconciled and signed off by Finance before cutover.", trace: "RSK-04 · Finance confirmation" },
  };
  return <div className="space-y-4">
    <Card className="overflow-hidden"><div className="flex flex-col gap-3 border-b border-[#e3e9ef] p-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><ClipboardList className="text-[#4c789c]"/><div><h2 className="font-bold text-[#203b59]">Requirement analysis register</h2><p className="text-sm text-[#7b8c9d]">Draft requirements created by the learner from analyzed findings; these are not the final BRD or URD.</p></div></div><Button variant="secondary">+ Add requirement</Button></div><div className="divide-y divide-[#e6edf2]">{requirements.map((item) => { const detail = details[item.id]; return <div key={item.id} className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div className="flex gap-3"><span className="grid h-10 min-w-10 place-items-center rounded-xl bg-[#e7f0f7] px-2 font-mono text-xs font-black text-[#3c6689]">{item.id}</span><div><div className="flex flex-wrap gap-2"><Badge tone="gray">{item.type}</Badge><Badge tone={item.priority === "Must" ? "red" : "amber"}>{item.priority}</Badge></div><h3 className="mt-2 font-bold text-[#334e69]">{item.title}</h3></div></div>{statusBadge(item.status)}</div><div className="mt-4 grid gap-3 lg:grid-cols-3"><div className="rounded-xl bg-[#f5f8fa] p-3"><p className="text-xs font-bold uppercase tracking-wide text-[#758a9e]">Rationale</p><p className="mt-2 text-sm leading-6 text-[#5d7388]">{detail?.rationale}</p></div><div className="rounded-xl bg-[#eef6f2] p-3"><p className="text-xs font-bold uppercase tracking-wide text-[#4f7b68]">Acceptance criteria</p><p className="mt-2 text-sm leading-6 text-[#587268]">{detail?.acceptance}</p></div><div className="rounded-xl bg-[#f2f4fa] p-3"><p className="text-xs font-bold uppercase tracking-wide text-[#68729b]">Source & trace</p><p className="mt-2 text-sm font-semibold leading-6 text-[#5b6588]">{detail?.trace}</p></div></div>{detail?.gap && <div className="mt-3 flex gap-2 rounded-xl border border-[#eadfc8] bg-[#fffaf1] p-3 text-sm text-[#75684f]"><AlertTriangle className="mt-0.5 shrink-0 text-[#9e6c22]" size={17}/>{detail.gap}</div>}</div>; })}</div></Card>
    <div className="grid gap-4 md:grid-cols-3"><Card className="p-5"><p className="text-xs font-bold uppercase tracking-wider text-[#71879d]">Source coverage</p><strong className="mt-2 block text-3xl text-[#274967]">4/5</strong><p className="mt-2 text-sm text-[#74879a]">Requirements have clear evidence and findings.</p></Card><Card className="p-5"><p className="text-xs font-bold uppercase tracking-wider text-[#71879d]">Measurable acceptance</p><strong className="mt-2 block text-3xl text-[#274967]">80%</strong><p className="mt-2 text-sm text-[#74879a]">NFR-03 still lacks a validated threshold.</p></Card><Card className="p-5"><p className="text-xs font-bold uppercase tracking-wider text-[#71879d]">AI/Expert assessment</p><p className="mt-3 text-sm leading-6 text-[#60758a]">Clarity, feasibility, testability, value alignment, and traceability to sources.</p></Card></div>
  </div>;
}

function ChangeImpactSection() {
  const impacts = [["Business objective","Stockout < 5% and fill rate ≥ 96% are at risk"],["Process","Transfer-first must run earlier and prioritize by region"],["Requirements","FR-08 must consider the promotion calendar and actual lead times"],["Data","Requires ATP by status, demand uplift, and supplier ETA"],["Stakeholders","Planner, Warehouse, Finance, Sales, and Director must validate"],["Risks","Stockouts, expediting costs, and unfair allocation across stores"]];
  const options = [["Transfer 1,800 units from the central warehouse","Arrives within two days and uses surplus stock","Transfer cost +9%; source region loses buffer","Preferred"],["Create an emergency purchase order","Preserves stock in other regions","High expediting fee; still four days late","Fallback"],["Limit promotional allocation","Protects priority stores","Affects Sales and customer experience","Only for remaining shortages"]];
  const consultations = [["Inventory Planner","Validate surplus stock and forecast uplift"],["Warehouse Manager","Capacity, cut-off, and transfer ETA"],["Finance Manager","Cost thresholds and approval"],["Sales Manager","Prioritize stores and promotions"]];
  const updates: Array<[string,string,boolean]> = [["Risk register","Add supplier delay and promotional stockout",true],["Decision log","Record the option to transfer 1,800 units",true],["Backlog / FR-08","Add promotion and ETA rules",false],["Acceptance criteria","Measure response time and fill rate",false]];
  return <div className="space-y-4">
    <Card className="overflow-hidden border-[#ead9bd]"><div className="bg-gradient-to-r from-[#fff4df] to-[#fffaf0] p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div className="flex gap-4"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-white text-[#a46e22] shadow-sm"><Truck size={23}/></span><div><p className="text-xs font-bold uppercase tracking-wider text-[#987039]">Dynamic event · 16/09 · 15:10</p><h2 className="mt-1 text-xl font-bold text-[#62491f]">MILK-01 supplier reports a five-day delay</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-[#77684f]">Available stock covers only three days, while the chain-wide promotion begins in seven days. The Sponsor asks the BA to reassess the MVP option before the executive meeting.</p></div></div><Badge tone="amber">In progress</Badge></div></div></Card>
    <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_350px]">
      <div className="space-y-5">
        <Card className="p-6"><div className="flex items-center gap-3"><RefreshCcw className="text-[#5c65a0]"/><h2 className="font-bold text-[#203b59]">Impact map</h2></div><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{impacts.map(([label,copy]) => <div key={label} className="rounded-xl border border-[#dfe7ee] bg-[#fafcfd] p-4"><p className="text-xs font-bold uppercase tracking-wide text-[#70869c]">{label}</p><p className="mt-2 text-sm leading-6 text-[#566e85]">{copy}</p></div>)}</div></Card>
        <Card className="overflow-hidden"><div className="border-b border-[#e3e9ef] p-5"><h2 className="font-bold text-[#203b59]">Option analysis & trade-off</h2><p className="mt-1 text-sm text-[#7b8c9d]">The BA compares impacts before recommending a decision.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[780px] text-left text-sm"><thead className="bg-[#f5f8fa] text-xs uppercase tracking-wider text-[#7a8da1]"><tr><th className="px-5 py-4">Option</th><th className="px-5 py-4">Benefit</th><th className="px-5 py-4">Trade-off</th><th className="px-5 py-4">Recommendation</th></tr></thead><tbody className="divide-y divide-[#e6edf2]">{options.map(([option,benefit,cost,recommendation]) => <tr key={option}><td className="px-5 py-4 font-bold text-[#3b5670]">{option}</td><td className="px-5 py-4 text-[#537163]">{benefit}</td><td className="px-5 py-4 text-[#75684f]">{cost}</td><td className="px-5 py-4"><Badge tone={recommendation === "Preferred" ? "green" : "navy"}>{recommendation}</Badge></td></tr>)}</tbody></table></div></Card>
      </div>
      <aside className="space-y-5"><Card className="p-5"><h2 className="font-bold text-[#203b59]">Stakeholders to Consult</h2><div className="mt-4 space-y-3">{consultations.map(([role,ask], index) => <div key={role} className="rounded-xl border border-[#e0e7ee] p-3"><div className="flex items-center justify-between"><strong className="text-sm text-[#3d5872]">{role}</strong><Badge tone={index < 2 ? "green" : "amber"}>{index < 2 ? "Consulted" : "To consult"}</Badge></div><p className="mt-2 text-xs leading-5 text-[#7a8c9e]">{ask}</p></div>)}</div></Card><Card className="p-5"><h2 className="font-bold text-[#203b59]">Artifacts to Update</h2><div className="mt-4 space-y-3">{updates.map(([name,copy,done]) => <div key={name} className="flex gap-3"><span className={`mt-0.5 grid h-5 w-5 shrink-0 place-items-center rounded-full ${done ? "bg-[#dcefe6] text-[#2d7658]" : "bg-[#fff0d9] text-[#9b691e]"}`}>{done ? <CheckCircle2 size={13}/> : <CircleHelp size={13}/>}</span><div><strong className="text-sm text-[#425c75]">{name}</strong><p className="mt-1 text-xs leading-5 text-[#7d8d9d]">{copy}</p></div></div>)}</div></Card></aside>
    </div>
  </div>;
}
