import { ArrowUpRight, Award, CheckCircle2, Download, Eye, Lightbulb, MessageCircleMore, Quote, RefreshCcw, Target } from "lucide-react";
import { babokScores } from "../../constants/scenario";
import { Badge } from "../../components/ui/Badge";
import { Button } from "../../components/ui/Button";
import { Card } from "../../components/ui/Card";
import { PageHeader } from "../../components/common/PageHeader";
import { ProgressBar } from "../../components/ui/ProgressBar";

const underlyingCompetencies = [
  ["Analytical Thinking & Problem Solving", 78, "Distinguishes facts from assumptions and identifies KPI conflicts"],
  ["Communication", 81, "Natural open questions, probing, and playback"],
  ["Interaction Skills", 76, "Facilitates warehouse–Finance disagreements using evidence"],
  ["Business Knowledge", 70, "Understands replenishment; needs deeper analysis of closed-period impacts"],
  ["Behavioral Characteristics", 74, "Proactively follows up and remains neutral in conflicts"],
  ["Tools & Technology", 68, "Uses traceability; needs to clarify offline behavior and idempotency"],
];

export function AssessmentPage() {
  return <>
    <PageHeader eyebrow="Session Results · INV-2026-014" title="Practice Competency Assessment" description="Results are derived from decisions, transcripts, evidence, and artifacts produced during the session; this is not a BABOK theory exam." actions={<Button variant="secondary"><Download size={16} />Export report</Button>} />
    <div className="grid gap-4 xl:grid-cols-[300px_minmax(0,1fr)]">
      <Card className="p-7 text-center"><span className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-[#e5eef6] text-[#315d86]"><Award size={27} /></span><p className="mt-5 text-sm font-semibold text-[#70849a]">Practice session performance</p><strong className="mt-1 block text-6xl font-bold tracking-[-.07em] text-[#1c3b5e]">72</strong><Badge tone="green">Meets expectations</Badge><p className="mt-5 text-sm leading-6 text-[#6e8093]">You handled stakeholder conflicts and evidence well. The main gaps are change-impact analysis and measuring MVP effectiveness after implementation.</p><div className="mt-6 border-t border-[#e3e9ef] pt-5 text-left"><div className="flex justify-between text-sm"><span className="text-[#77899c]">AI evidence score</span><strong>71</strong></div><div className="mt-3 flex justify-between text-sm"><span className="text-[#77899c]">Instructor moderation</span><strong>73</strong></div></div></Card>
      <Card className="p-6"><div className="flex items-center justify-between"><div><h2 className="text-lg font-bold text-[#203b59]">Application Across Six Knowledge Areas</h2><p className="mt-1 text-sm text-[#7c8d9e]">Assesses how knowledge is applied in a business context.</p></div><span className="text-xs text-[#8292a3]">Confidence 0.86</span></div><div className="mt-6 grid gap-x-8 gap-y-5 md:grid-cols-2">{babokScores.map((skill) => <div key={skill.short}><div className="mb-2 flex justify-between text-sm"><span className="text-[#526a82]">{skill.name}</span><strong className="text-[#274867]">{skill.score}</strong></div><ProgressBar value={skill.score} color={skill.score >= 70 ? "#4f779d" : skill.score >= 60 ? "#7d9ab5" : "#b2c2d1"} /></div>)}</div></Card>
    </div>

    <Card className="mt-5 p-6"><div className="flex items-center gap-3"><Eye className="text-[#4d7599]"/><div><h2 className="text-lg font-bold text-[#203b59]">Observed Underlying Competencies</h2><p className="text-sm text-[#7b8c9d]">Competency is demonstrated through behavior, not memorized definitions.</p></div></div><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{underlyingCompetencies.map(([name, score, evidence]) => <div key={String(name)} className="rounded-xl border border-[#dfe7ee] p-4"><div className="flex items-start justify-between gap-3"><strong className="text-sm leading-5 text-[#3d5771]">{String(name)}</strong><span className="text-lg font-black text-[#315a7e]">{String(score)}</span></div><div className="mt-3"><ProgressBar value={Number(score)} /></div><p className="mt-3 text-xs leading-5 text-[#77899b]">{String(evidence)}</p></div>)}</div></Card>

    <div className="mt-4 grid gap-4 lg:grid-cols-2">
      <Card className="p-6"><div className="flex items-center gap-3"><CheckCircle2 className="text-[#2f7b5a]" /><h2 className="text-lg font-bold text-[#203b59]">Evidence-Based Strengths</h2></div><div className="mt-5 space-y-4">{[["Elicitation quality","You used open questions and follow-ups to uncover that returns are updated only at the end of the shift."],["Conflict resolution","You balanced warehouse processing speed with Finance segregation-of-duties controls."],["Traceability","Four of five business requirements are linked to transcript evidence and business objectives."]].map(([title,copy]) => <div key={title} className="rounded-xl bg-[#f5f8fa] p-4"><strong className="text-sm text-[#36516d]">{title}</strong><p className="mt-2 text-sm leading-6 text-[#6a7d91]">{copy}</p><button className="mt-2 flex items-center gap-1 text-xs font-semibold text-[#51779b]"><Quote size={13} />Open source evidence</button></div>)}</div></Card>
      <Card className="p-6"><div className="flex items-center gap-3"><Target className="text-[#9a6a19]" /><h2 className="text-lg font-bold text-[#203b59]">Improvement Opportunities</h2></div><div className="mt-5 space-y-4">{[["Solution Evaluation","The baseline and post-launch MVP effectiveness measures have not been defined."],["Acceptance criteria","Two requirements still use “fast” and “easy to use” without measurable thresholds."],["Change impact","The supplier-delay event has not been fully reflected in the risk log and backlog."]].map(([title,copy]) => <div key={title} className="rounded-xl border border-[#eadfc7] bg-[#fffaf0] p-4"><strong className="text-sm text-[#654d20]">{title}</strong><p className="mt-2 text-sm leading-6 text-[#7a6c52]">{copy}</p><button className="mt-2 flex items-center gap-1 text-xs font-semibold text-[#80652c]">View evidence-based guidance <ArrowUpRight size={13} /></button></div>)}</div></Card>
    </div>

    <Card className="mt-5 overflow-hidden"><div className="border-b border-[#e2e9ef] bg-[#f5f8fb] p-6"><div className="flex items-center gap-3"><MessageCircleMore className="text-[#5f649b]"/><div><h2 className="text-lg font-bold text-[#203b59]">Debrief: What Happened in the Business?</h2><p className="text-sm text-[#778a9d]">Compare your decisions with missed signals and stakeholder feedback.</p></div></div></div><div className="grid gap-5 p-6 lg:grid-cols-3"><div><p className="text-xs font-bold uppercase tracking-wider text-[#74899e]">Missed signals</p><ul className="mt-3 space-y-3 text-sm leading-6 text-[#5e7489]"><li>• Finance noted that the accounting period might already be locked.</li><li>• Legacy scanners do not display the pending queue.</li><li>• The MILK-01 promotion starts in seven days.</li></ul></div><div><p className="text-xs font-bold uppercase tracking-wider text-[#74899e]">Stakeholder feedback</p><p className="mt-3 rounded-xl bg-[#edf5fa] p-4 text-sm italic leading-6 text-[#536d84]">“The transfer-first option makes sense, but I need to see who can override it and how that decision affects holding cost.” — Supply Chain Director</p></div><div><p className="text-xs font-bold uppercase tracking-wider text-[#74899e]">Self-reflection</p><textarea className="mt-3 min-h-28 w-full rounded-xl border border-[#dce5ed] bg-white p-3 text-sm text-[#455f78] outline-none" defaultValue="If I did this again, I would confirm the promotion calendar and period lock before finalizing the option..."/><button className="mt-2 text-xs font-bold text-[#53789a]">Save reflection</button></div></div></Card>

    <Card className="mt-5 flex flex-col gap-5 p-6 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-4"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-[#e9f0f6] text-[#51779b]"><Lightbulb size={20} /></span><div><h2 className="font-bold text-[#203b59]">Next Experience</h2><p className="mt-2 leading-6 text-[#687c91]">Replay the supplier-delay event to try another option, or continue to the “Lot Control and Product Recall” scenario to broaden your traceability and risk experience.</p></div></div><Button variant="secondary"><RefreshCcw size={16}/>Replay from checkpoint</Button></Card>
  </>;
}
