import type { LearningApplication, LearningDomain } from "../types/models";

export const learningDomains: LearningDomain[] = [
  { id: "supply-chain", name: "Supply Chain", shortName: "Supply Chain", description: "From purchasing and inventory to transportation and demand forecasting.", icon: "boxes", color: "#315f88", applicationIds: ["inventory", "purchase", "logistics", "demand-planning"] },
  { id: "sales-customer", name: "Sales & Customer", shortName: "Sales & Customer", description: "Manage leads, opportunities, orders, and customer experience.", icon: "sales", color: "#7a5b9e", applicationIds: ["crm", "sales", "pos", "ecommerce"] },
  { id: "finance", name: "Finance & Accounting", shortName: "Finance", description: "Invoices, receivables, expenses, and financial controls.", icon: "finance", color: "#2d7b73", applicationIds: ["accounting", "invoicing", "expenses", "budgeting"] },
  { id: "manufacturing", name: "Manufacturing", shortName: "Manufacturing", description: "Production planning, quality, and equipment maintenance.", icon: "factory", color: "#a8643d", applicationIds: ["mrp", "quality", "maintenance", "plm"] },
  { id: "human-resources", name: "Human Resources", shortName: "Human Resources", description: "Recruitment, employee records, time off, and performance.", icon: "people", color: "#4d6fa8", applicationIds: ["recruitment", "employees", "time-off", "performance"] },
  { id: "project-operations", name: "Project Operations", shortName: "Project Operations", description: "Projects, timesheets, field services, and support operations.", icon: "project", color: "#7b6a47", applicationIds: ["project", "timesheets", "field-service", "helpdesk"] },
];

export const learningApplications: LearningApplication[] = [
  { id: "inventory", domainId: "supply-chain", name: "Inventory Management", description: "Analyze stockouts, replenishment, warehouse transfers, and traceability.", scenarioCount: 8, level: "Intermediate", duration: "6 hours", progress: 42, status: "available", accent: "#315f88" },
  { id: "purchase", domainId: "supply-chain", name: "Purchasing", description: "From purchase requests to supplier selection and receiving.", scenarioCount: 6, level: "Beginner", duration: "4 hours", progress: 0, status: "beta", accent: "#4779a3" },
  { id: "logistics", domainId: "supply-chain", name: "Logistics & Transportation", description: "Optimize delivery, routing, and shipment exceptions.", scenarioCount: 5, level: "Advanced", duration: "5 hours", progress: 0, status: "coming-soon", accent: "#5b86a8" },
  { id: "demand-planning", domainId: "supply-chain", name: "Demand Planning", description: "Forecast demand and balance supply across multiple warehouses.", scenarioCount: 7, level: "Advanced", duration: "7 hours", progress: 0, status: "coming-soon", accent: "#406887" },
  { id: "crm", domainId: "sales-customer", name: "CRM", description: "Explore lead, pipeline, and sales activity management needs.", scenarioCount: 7, level: "Beginner", duration: "5 hours", progress: 0, status: "beta", accent: "#7a5b9e" },
  { id: "sales", domainId: "sales-customer", name: "Sales Management", description: "Quotations, sales orders, pricing policies, and approval flows.", scenarioCount: 6, level: "Intermediate", duration: "5 hours", progress: 0, status: "coming-soon", accent: "#8a6baa" },
  { id: "pos", domainId: "sales-customer", name: "Point of Sale", description: "Analyze multi-store retail flows and inventory synchronization.", scenarioCount: 4, level: "Intermediate", duration: "3 hours", progress: 0, status: "coming-soon", accent: "#6f5a91" },
  { id: "ecommerce", domainId: "sales-customer", name: "E-commerce", description: "Omnichannel shopping, payment, and returns journeys.", scenarioCount: 5, level: "Intermediate", duration: "4 hours", progress: 0, status: "coming-soon", accent: "#8866a4" },
  { id: "accounting", domainId: "finance", name: "Accounting", description: "General ledger, reconciliation, accounting periods, and reporting.", scenarioCount: 8, level: "Advanced", duration: "8 hours", progress: 0, status: "beta", accent: "#2d7b73" },
  { id: "invoicing", domainId: "finance", name: "Invoicing", description: "Invoice creation, payment, and receivables management.", scenarioCount: 5, level: "Beginner", duration: "4 hours", progress: 0, status: "coming-soon", accent: "#3e8a82" },
  { id: "expenses", domainId: "finance", name: "Expenses", description: "Employee expense submission, review, and approval.", scenarioCount: 4, level: "Beginner", duration: "3 hours", progress: 0, status: "coming-soon", accent: "#548f88" },
  { id: "budgeting", domainId: "finance", name: "Budgeting", description: "Budget planning, allocation, and variance tracking.", scenarioCount: 6, level: "Advanced", duration: "6 hours", progress: 0, status: "coming-soon", accent: "#37756f" },
  { id: "mrp", domainId: "manufacturing", name: "Manufacturing Planning", description: "BOMs, work orders, capacity, and material planning.", scenarioCount: 8, level: "Advanced", duration: "8 hours", progress: 0, status: "beta", accent: "#a8643d" },
  { id: "quality", domainId: "manufacturing", name: "Quality Management", description: "Quality checkpoints, criteria, and nonconformance handling.", scenarioCount: 5, level: "Intermediate", duration: "4 hours", progress: 0, status: "coming-soon", accent: "#b4734b" },
  { id: "maintenance", domainId: "manufacturing", name: "Maintenance", description: "Preventive maintenance, incidents, and equipment performance.", scenarioCount: 5, level: "Intermediate", duration: "4 hours", progress: 0, status: "coming-soon", accent: "#9d704f" },
  { id: "plm", domainId: "manufacturing", name: "Product Lifecycle", description: "Engineering changes and product design version control.", scenarioCount: 4, level: "Advanced", duration: "4 hours", progress: 0, status: "coming-soon", accent: "#98613e" },
  { id: "recruitment", domainId: "human-resources", name: "Recruitment", description: "Hiring requests, candidate pipelines, and selection decisions.", scenarioCount: 5, level: "Beginner", duration: "4 hours", progress: 0, status: "beta", accent: "#4d6fa8" },
  { id: "employees", domainId: "human-resources", name: "Employee Records", description: "Employee data, contracts, and employment lifecycle.", scenarioCount: 4, level: "Beginner", duration: "3 hours", progress: 0, status: "coming-soon", accent: "#5f7fb4" },
  { id: "time-off", domainId: "human-resources", name: "Time Off", description: "Leave policies, approvals, and workforce balancing.", scenarioCount: 3, level: "Beginner", duration: "2 hours", progress: 0, status: "coming-soon", accent: "#6882ad" },
  { id: "performance", domainId: "human-resources", name: "Performance", description: "Goals, periodic reviews, and development planning.", scenarioCount: 5, level: "Intermediate", duration: "4 hours", progress: 0, status: "coming-soon", accent: "#4c6696" },
  { id: "project", domainId: "project-operations", name: "Project Management", description: "Scope, work, dependencies, and schedule control.", scenarioCount: 7, level: "Intermediate", duration: "6 hours", progress: 0, status: "beta", accent: "#7b6a47" },
  { id: "timesheets", domainId: "project-operations", name: "Timesheets", description: "Time capture, approval, and project cost analysis.", scenarioCount: 4, level: "Beginner", duration: "3 hours", progress: 0, status: "coming-soon", accent: "#897957" },
  { id: "field-service", domainId: "project-operations", name: "Field Service", description: "Technician dispatch, appointments, and service acceptance.", scenarioCount: 5, level: "Intermediate", duration: "4 hours", progress: 0, status: "coming-soon", accent: "#74664a" },
  { id: "helpdesk", domainId: "project-operations", name: "Helpdesk", description: "Ticket intake, SLAs, classification, and support resolution.", scenarioCount: 5, level: "Beginner", duration: "4 hours", progress: 0, status: "coming-soon", accent: "#8b7953" },
];
