import { ArrowRight, Check, ClipboardList, Database, FileQuestion, Lightbulb, Target, Users } from "lucide-react";
import { Button } from "../../components/ui/Button";
import { Card } from "../../components/ui/Card";
import { PageHeader } from "../../components/common/PageHeader";
import { stakeholders } from "../../constants/scenario";
import { scenarioObjectives } from "../../constants/trainingScenario";
import type { RouteKey } from "../../types/models";

export function PlanningPage({ navigate }: { navigate: (route: RouteKey) => void }) {
  const sessions = [
    ["Warehouse Manager","Interview + playback","As-Is receiving, picking, returns, inventory status, and exceptions","Process map · pain points · evidence"],
    ["Inventory Planner","Decision analysis","Forecast, min-max, transfer vs. PO, and promotions","Decision table · business rules"],
    ["Finance Manager","Rules workshop","Approval thresholds, audit trail, and period lock","Rule catalog · control requirements"],
    ["Supply Chain Director","KPI elicitation","Targets, pilot scope, and override authority","Objectives · scope · acceptance"],
    ["Warehouse Operator","Observation","Offline scanning, devices, and workarounds","Task steps · usability/NFR"],
    ["Project Sponsor","Interview","Budget, timeline, out-of-scope items, and governance","Constraints · decision rights"],
  ];
  return <><PageHeader eyebrow="Step 1 of 5 · BA Planning & Monitoring" title="Plan Business Analysis" description="Define measurable objectives, stakeholders, techniques, question sets, and the evidence to collect before starting." />
  <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_310px]"><div className="space-y-4">
    <Card className="p-6"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#e9f1f8] text-[#456d94]"><Target size={20}/></span><h2 className="text-lg font-bold text-[#1d3858]">Business objectives & success measures</h2></div><textarea className="mt-5 min-h-20 w-full rounded-xl border border-[#d9e3ec] bg-[#fafcfd] p-4 text-sm leading-6 text-[#304966] outline-none" defaultValue="Identify the causes of stockouts and design a replenishment process that prioritizes internal transfers before creating new purchase orders without increasing inventory-control risk."/><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{scenarioObjectives.map((item) => <div key={item.label} className="rounded-xl border border-[#dfe7ee] p-3"><p className="text-xs font-bold text-[#71869b]">{item.label}</p><p className="mt-2 text-sm text-[#8291a0]"><span className="line-through">{item.baseline}</span> <ArrowRight className="inline" size={13}/> <strong className="text-[#2c664f]">{item.target}</strong></p><p className="mt-2 text-[11px] text-[#8a98a6]">Owner: {item.owner}</p></div>)}</div></Card>
    <Card className="overflow-hidden"><div className="flex items-center gap-3 border-b border-[#e3e9ef] p-5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#edf4f8] text-[#4b759a]"><Users size={20}/></span><div><h2 className="font-bold text-[#203b59]">Stakeholder elicitation plan</h2><p className="text-sm text-[#7d8d9e]">Every session must have a clear objective and expected outcome.</p></div></div><div className="overflow-x-auto"><table className="w-full min-w-[860px] text-left text-sm"><thead className="bg-[#f5f8fa] text-xs uppercase text-[#7b8da0]"><tr><th className="px-5 py-3">Stakeholder</th><th className="px-5 py-3">Technique</th><th className="px-5 py-3">Information to collect</th><th className="px-5 py-3">Output</th></tr></thead><tbody className="divide-y divide-[#e5ecf1]">{sessions.map((row) => <tr key={row[0]}><td className="px-5 py-4 font-bold text-[#39536d]">{row[0]}</td><td className="px-5 py-4 text-[#4c7397]">{row[1]}</td><td className="px-5 py-4 text-[#5e7388]">{row[2]}</td><td className="px-5 py-4 text-[#5e7388]">{row[3]}</td></tr>)}</tbody></table></div></Card>
    <div className="grid gap-5 lg:grid-cols-2"><Card className="p-6"><div className="flex items-center gap-3"><FileQuestion className="text-[#6970a6]"/><h2 className="font-bold text-[#203b59]">Question bank</h2></div><div className="mt-4 space-y-3">{[["Process","Please describe each step from demand identification to goods issue."],["Pain point","At which step do discrepancies usually occur, and what are the consequences?"],["Rule","Which data or thresholds trigger a transfer instead of a purchase order?"],["Exception","How is the process handled when the network is unavailable or the accounting period is locked?"],["Confirmation","My understanding is… Is that correct?"]].map(([type,q]) => <div key={type} className="rounded-xl bg-[#f5f8fa] p-3"><span className="text-[10px] font-bold uppercase text-[#71879d]">{type}</span><p className="mt-1 text-sm text-[#506980]">{q}</p></div>)}</div></Card><Card className="p-6"><div className="flex items-center gap-3"><Database className="text-[#427e6a]"/><h2 className="font-bold text-[#203b59]">Documents and data to request</h2></div><div className="mt-4 space-y-3">{["POS transactions and latency logs for 3 months","Inventory snapshots and cycle-count variances","8-week forecast, min-max settings, and promotion calendar","Transfer orders, purchase orders, and supplier lead times","Inventory adjustments and audit trail","Return/quarantine SOP and approval matrix"].map((item,index) => <label key={item} className="flex items-start gap-3 rounded-xl border border-[#e0e8ee] p-3"><input type="checkbox" defaultChecked={index < 4} className="mt-1 accent-[#376489]"/><span className="text-sm text-[#576f86]">{item}</span></label>)}</div></Card></div>
  </div><aside className="space-y-5"><Card className="p-6"><p className="text-xs font-bold uppercase tracking-wider text-[#6e86a0]">Readiness gate · 5/6</p><div className="mt-5 space-y-4">{["Objectives include baselines and targets","Stakeholder map includes all decision-makers","Techniques align with each objective","Question bank includes probing and confirmation","Data requests have been sent","Initial assumptions have sponsor approval"].map((item,index) => <div key={item} className="flex items-start gap-3"><span className={`mt-0.5 grid h-5 w-5 place-items-center rounded-full ${index < 5 ? "bg-[#dcedf8] text-[#315f88]" : "bg-[#fff0d9] text-[#a06b1b]"}`}>{index < 5 && <Check size={13}/>}</span><span className="text-sm text-[#5f748b]">{item}</span></div>)}</div><Button onClick={() => navigate("simulation")} className="mt-7 w-full">Start simulation <ArrowRight size={16}/></Button></Card><Card className="p-5"><div className="flex gap-3"><Lightbulb className="shrink-0 text-[#8a6a21]" size={19}/><p className="text-sm leading-6 text-[#6c7d8f]">Do not begin by asking, “What do you want the system to have?” First understand the work, decisions, data, rules, exceptions, and success criteria.</p></div></Card><Card className="p-5"><div className="flex gap-3"><ClipboardList className="shrink-0 text-[#4f779a]" size={19}/><div><p className="font-bold text-[#36516c]">Assumptions to validate</p><ul className="mt-2 space-y-2 text-sm leading-5 text-[#6c7d8f]"><li>• POS latency is the primary cause</li><li>• All warehouses use the same SKU codes</li><li>• A transfer is always cheaper than a purchase order</li></ul></div></div></Card></aside></div></>;
}
